apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fleet-api.fullname" . }}
  labels:
    {{- include "fleet-api.labels" . | nindent 4 }}
data:
  AWS_REGION: {{ .Values.config.awsRegion | quote }}
  DYNAMODB_TABLE: {{ .Values.config.dynamodbTable | quote }}
  S3_BUCKET: {{ .Values.config.s3Bucket | quote }}
  AWS_ENDPOINT_URL: {{ .Values.config.awsEndpointUrl | quote }}
